version: "3"

services: 
    nginx:
        image: nginx:alpine
        ports: 
            - 80:80
        volumes: 
            - ../backend:/var/www/html/backend
            - ./nginx:/etc/nginx/conf.d
        restart: unless-stopped
    backend:
        build: ../backend
        volumes: 
            - ../backend:/var/www/html/backend
        expose: 
            - 9000
        restart: unless-stopped
    frontend:
        build: ../frontend
        restart: unless-stopped
        stdin_open: true
        # ports:
        #     - 3000:3000
        volumes: 
            - ../frontend:/usr/src/app
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        volumes: 
            - ../db/dbdata:/var/lib/mysql/
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "BTL"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
        ports: 
            - 3306:3306
        restart: unless-stopped
    
